### ISSUE TITLE
オンライン版資料の基本方針

### ISSUE THREAD

**Issue by tomcha** [perl-entrance-org/workshop-basic-online#1]
現行テキストに対して、オンライン版に変更するにあたりどの様に変化させるのかの基本方針を考えてみました。意見、その他アイデア出し等お願いします。

- 環境構築はバッサリとカット（過去の資料の導線を案内し、環境構築したい人は自習してもらう）
    - 自力で環境構築出来ない人はオンライン開発環境（wandboxなど）で学習
- 練習問題をできるだけ多くする
    - 少しでも多く手を動かす場を提供する、自習・復習も考慮した資料作り
- Mojolicious回をカット（オンライン開発環境では不可のため）
    - webアプリ編をやるなら、アドバンス版に別途作成してはどうか

**Comment by yuki-kimoto** [comment]
オンライン版を新しく作るという認識でよいでしょうか?

**Comment by tomcha** [comment]
そうです。オンラインで入学式をやるとすると、現行と同じテキストでは難しいかと思いますので。

**Comment by yuki-kimoto** [comment]
インストールが難関なので、Perlが実行できるWebサービスを使えば、Perlをすぐに実行できるというアイデアを一つ提案します。

(というか、よく考えると、これは、トムチャさんのアイデアそのままでした。)

**Comment by xtetsuji** [comment]
すっかり Issue 放置していましたが、当初挙げてもらったことはこの2年間で結構実現できましたね。

- 環境構築カット
    - Wandbox 案を進め、結果的に手元に Perl 環境を作ることを支援したいよねということで Windows 向けには MSYS2 復活
- Mojolicious 回カット
    - API と Webhook がよくまとまっているので、今の資料はいい感じ
    - ウェブはウェブアプリという巨大なカリキュラムとしてアドバンスド版独立も良いアイデア
