### ISSUE TITLE
#4 資料デリファレンスで->を使わない記法の解説を取りやめる

### ISSUE THREAD

**Issue by tomcha** [perl-entrance-org/workshop-basic-online#40]
リファレンス（配列リファレンス、ハッシュリファレンス）から個別の値にアクセスする方法として、->を使わない方法が紹介されていますが、一般的ではない記法の様なので記載しない方が良いのかなと思いました。
 print "${$array_ref}[0]\n";  
 print ${$hash_ref}{name}; 
↑
コレ

色んな記法が紹介されると混乱してしまう可能性があるのかなと思います。
実際、自分が初学者の時、通常の配列・ハッシュからのアクセス時（矢印無し）とリファレンスからの参照時（矢印有り）がごっちゃになって覚えて苦労した経験もあったのでissue立ててみました。
この解説をする様になった経緯もあるかと思うので、議論できればと思います。

**Comment by tomcha** [comment]
$array_ref リファレンスをデリファレンスすると@{$array_ref}。
@sample 配列の3番目の要素にアクセスする時は、@を$に変えて $sample[3]と書く。 
@{$array_ref}を普通の配列と見立てて、同様にすると、${$array_ref}[3]となる。

という3段階の思考を経ての記法（説明）ということですかね。

**Comment by xtetsuji** [comment]
アロー `->` を使う使わないという部分の差異、違う理由で2通りあると思ったので、ちょっと長くなりますが前提の整理のためにまとめます。

# アロー記法ありなしの2通り

## デリファレンスのシジルが込み入るのを単純に除去したい（シジル略記パターン）

最初は **デリファレンスのシジルが込み入るのを単純に除去したい** ケース。これはアロー記法導入の当初の目的です。

例えば `$hashref` にハッシュリファレンスが代入されている場合、キー `key` の値を取り出すには

- `%{$hashref}` がデリファレンスしたハッシュ
- ハッシュ `%hash` の特定の `key` にアクセスする `$hash{key}` の類推で `${$hashref}{key}`
- この `${$hashref}{key}` を `$hashref->{key}` と略記できる

という文法的解釈ができますが、 `${$hashref}{key}` を `$hashref->{key}` と書ける、逆に言えば `${$hashref}{key}}` という書き方だとアローが入らないということになります。

デリファレンスのシジル `%` が `$` になって…というのが分かりづらいので、それを意味的に含んだアローを使った書き方が見やすいだろうという文法です。

## データ的に入れ子になった要素で自明な略記をする（深部リファレンス暗黙パターン）

次に本来必要なアローを省略できる、**データ的に入れ子になった要素で自明な略記をする** ケース。

例えば、 `${$hashref}{key1}` または同等の `$hashref->{key1}` を評価した値もハッシュリファレンスだった場合、新たに得られたハッシュリファレンスのキーをたどる際に、上記同様に考えると段階的に以下の書き方があると思います。

- `${${$hashref}{key1}}{key2}`
- `${$hashref->{key1}}{key2}` または `${$hashref}{key1}->{key2}`
- `$hashref->{key1}->{key2}`

リファレンス構造が2段階だとシジルが複数出てくる書き方はややこしさが倍増するのもあり、最後の `->` を使った記法がさらに簡素ですね。

Perl では、入れ子になった複雑なデータ構造の2段階目以降にはリファレンス構造しか置けないので、 `$hashref->{key1}->{key2}` という表記において、`$hashref` と `{key1}` の間のアローはその有無で指している変数の意味が変わります（後述）が、同様に2段階目以降がリファレンス構造であることが確定しているので `{key1}` と `{key2}` の間のアローは有って当然、それが無かった場合に別の意味として解釈される状況が存在しません。よって、後者の省略を文法エラーにしても良かったのですが、書かなくても意図が通じるということで省略可能、つまり `$hashref->{key1}->{key2}` と `#hashref->{key1}{key2}` は同じものを指すというルールができました。

こちらはアローが無くても文法的に迷いがないので、書くのをサボっても良いという文法です。

入れ子構造は配列であっても同じであり、配列とハッシュを混用しても同じです。なので、このルールを一言で表すと、 **インデックスやキーを指定する括弧の `]` や `}` と `[` や `{` の間にある `->` は省略しても文法的に同じ** と言えます。

上記の括弧間アロー省略のルールで理解すれば問題ないですが、`$hashref` と `{key1}` の間のアローは省略できません。これは以下のソースコードで分かります。

```perl
use strict;
use warnigns;
use feature qw(say);
my %h = (
    key1 => {key2 => "Hello"}
);
my $h = {
    key2 => {key2 => "Bonjour"}
};
say $h{key1}->{key2}; # => Hello
say $h->{key1}->{key2}; # => Bonjour
```

シジルが違えば同じ名前を付けられるという Perl のルールに引きずられている部分です。

# 各ケースでアロー記法を選ぶかどうか

導入の発想的には、前者のシジル頻出防止ではアロー導入で見やすくしたい、後者の入れ子途中のアローが文法上無くても良いならアロー省略で書くのを楽したいという別の文法だと言えましょう。xtetsuji 用語ではありますが、 **便宜上、前者を「シジル略記パターン」、後者を「深部リファレンス暗黙パターン」と呼ぶ** ことにします。

**シジル略記パターンでアローを使うべきというのは大多数の総意** だと思います。もちろん、 `delete` `scalar` `keys` `values` といった配列やハッシュの操作関数に与える必要があるのはリファレンス構造ではなくてそれをデリファレンスしたものなので、 `keys %{$hashref}` といったデリファレンスは現役ですが、デリファレンスした構造の枝葉を `${$hashref}{key1}` で取り出すより `$hashref->{key1}` とした方が良いのは多数派というか、ほぼ全員がそう書いている印象です。

深部リファレンス暗黙パターンの場合はどうでしょう。こちらはアローを書かないことで楽ができるという配慮の文法です。しかし、 **私の知っている Perl プログラマの多くはこの深部リファレンス暗黙パターンでもアローを書く人が多いように思えます** 。かくいう私も書いています。全員がそうではなく省略している人も見受けられますが、書く理由は以下のような理由があるのではないかと想定しています。

- 意味的に枝葉アクセスのためのデリファレンスを明示したほうが好ましい
- 特に波括弧 `{}` はハッシュのキー指定の他に、ハッシュリファレンスのリテラル、ブロックの明示、シジルの明示範囲など意味が多く、局所的に読むときに前後にアローがあると読みやすさがある
- 省略できるというオプショナルな文法だと、省略する場合としない場合がまちまちになったときに読みづらさは確実にあるので、最初から省略しないというコーディングルールを敷いたほうがよい
- Postfix Dereference で最後に `->@*` とかするときに、最後のアローが文法上省略できないので `$context->{response}{body}{lines}->@*` とするなら最初から全部入れた `$context->{response}->{body}->{lines}->@*` ほうが見栄えが良い

これに漏れる例もあると思っていて、例えば2次元配列を模した構造を、各要素が配列リファレンスの配列で作成したときは、アローがない方が読みやすいのでそれを採用するといった例外はあるかなと思います。

```perl
my @matrix = (
   [1, 2, 3],
   [4, 5, 6],
   [7, 8, 9]
);
say $matrix[1][1]; # => 5
```

（蛇足ですが、参照の形で配列を扱えるプログラミング言語にて、配列の要素に配列を置くことで作る上記のような「多次元配列」は擬似的であるとされることもあります。）

# Perl入学式でどう教えると良いか

ようやく Issue の本題に入りましたが、今までの解説を見ていくと大方針は以下のようにしたいなと考えています。

- 世間でメジャーなコーディングスタイルにならって、「シジル略記パターン」も「深部リファレンス暗黙パターン」もアローを書くスタイルを前面に押し出す
- ただし、「シジル略記パターン」の意味的なデリファレンスを理解していない場合、 `keys %{$hashref}` 等が唐突になる考察はすべき

どちらのパターンでもアローを書くだけでなく、教える順序もアローを書く方からで大丈夫かなと考えています。

もちろん細部で不備や混乱が発生する可能性があるので多少慎重に検討したいなと思っていて、その一つが配列やハッシュの操作関数にリファレンス構造を与える時の `keys %{$hashref}` という記法かなと検討しています。ここを「そういうものか」と納得させられる記述が書ければ大丈夫そうという認識でいます。

アロー記法をメインに教える場合は、明示的にシジルでデリファレンスをする「シジル略記パターン」の裏側について、スライド巻末の落穂拾いや副読本などでフォローできればと考えています。

スライド巻末の落穂拾いは便利な場所ではありますが、スライド分量全体から計算する上での講義時の時間配分の混乱になったり、受講生にどこまでが必修かが分からなかったりするかもしれないので、別のスライドに分けたり副読本や参考サイトの作成などを通してフォローしていければと考えています。別のスライドは sironekotoro さんの副読スライドのようなものを想定しています。副読本があれば同人頒布などの別の展開も考えられると思っていて、これもまた興味深いです。

Perl は Perl 4 までの配列やハッシュ（当時は連想配列でしたが）の操作関数があり、Perl 5 で複雑なデータ構造やオブジェクト指向のためにリファレンスを導入するという流れで、配列やハッシュとそのリファレンスの扱いが複雑になってしまった経緯があります。これは仕方がない部分であり、これを非互換変更で捨て去らないところも Perl の良いところではあるのですが、今から学ぶ上では足かせになっている部分は大いに有って悩ましいところです。

Perl の配列やハッシュは素朴な値渡しですが、メジャーなプログラミング言語のように配列やハッシュを参照構造で取り扱う、つまり配列リファレンスやハッシュリファレンスを最初に教えて、配列やハッシュは過去との互換性の一環で教えるという教育スタイルも考えられると思います。とはいえ、リファレンスではない配列やハッシュを教えないと操作関数系が奇妙な見え方になってしまい、かつ配列やハッシュを使うお手軽なコードを読み書きできないというツラさもあり、私がこの教育スタイルに全面的に賛同できない理由となっています。

アロー記法で統一しつつ操作関数系の唐突なデリファレンスのシジルを無くす上で Postfix Dereference は有用かと思うのですが、Perl 5.14 以降であること以上に、現役 Perl プログラマ内での Postfix Dereference の評価が微妙なラインで、私がこれを Perl入学式の場で提唱することにはなお躊躇があります。

```perl
for my $key (keys $hashref->{key1}->%*) { # keys %{$hashref-{key1}} と同じ
    ...
}
for my $element ($hashref->{elements}->@*) { # @{$hashref->{elements}} と同じ
    ...
}
```

**Comment by tomcha** [comment]
現行資料の経緯が分かったのと、今の所大きな問題は無いことが分かったので、issueはCloseします。
アローなしセクション（解説）とアロー記法のセクション、順番を入れ替えるか否かのアイデアは、必要に応じて別途issueを立てましょう。
