### ISSUE TITLE
資料を第n回形式から章毎のmdファイル形式に変更する

### ISSUE THREAD

**Issue by tomcha** [perl-entrance-org/workshop-basic-online#41]
資料及び開催内容の区切りを、現行の第n回区切りを辞めて、章毎の区切りに変更していきます。
ファイル名は、章のタイトル.mdファイルとします。
オンライン版で上手く運用できれば、オフライン版と統合も視野に入れて修正していきましょう。

**Comment by xtetsuji** [comment]
分割基準は、各回2〜3個ある大きなまとまりの節かなと考えています。粒度としては

順番を奇想させるような番号をファイル名に入れるかなどは要考察です。 `stdin.md` にするか `04-stdin.md` にするかといった内容。

分割は良いなと思ったのですが、現行の Revealup だと同じ収録日の生放送中にスライドを切り替える負担がかなり大きいことに気づきました。この辺りスライドツールをいじるなどして切り替えの負担が低くなるようにしたいです。

**Comment by xtetsuji** [comment]
こちら、昨年秋頃から @sironekotoro さんがファイル分割を試みて一定の成果があるのでクローズします。
